# Generated by Django 2.0.5 on 2018-05-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0002_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedvideo',
            options={'verbose_name': 'embed video', 'verbose_name_plural': 'embed videos'},
        ),
    ]
